"""add returned and purchased quantity to conditional items

Revision ID: 9875ad3b823e
Revises: f984f0f4c57e
Create Date: 2025-12-13 19:13:52.241273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9875ad3b823e'
down_revision = 'f984f0f4c57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conditional_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purchased_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conditional_items', schema=None) as batch_op:
        batch_op.drop_column('purchased_quantity')
        batch_op.drop_column('returned_quantity')

    # ### end Alembic commands ###
