"""create products cache

Revision ID: f984f0f4c57e
Revises: e6a576d3541e
Create Date: 2025-12-05 21:22:44.278749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f984f0f4c57e'
down_revision = 'e6a576d3541e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('brand')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
